#define TOK_EOL                              1
#define TOK_IMPORT                           2
#define TOK_FROM                             3
#define TOK_COMMA                            4
#define TOK_FUNC                             5
#define TOK_ID                               6
#define TOK_LPAR                             7
#define TOK_RPAR                             8
#define TOK_ABSTRACT                         9
#define TOK_END                             10
#define TOK_PROC                            11
#define TOK_EVENT                           12
#define TOK_LOCAL                           13
#define TOK_OBSERVER                        14
#define TOK_CONST                           15
#define TOK_AT                              16
#define TOK_ASSIGN                          17
#define TOK_DOT                             18
#define TOK_MULT                            19
#define TOK_LT                              20
#define TOK_GT                              21
#define TOK_CLASS                           22
#define TOK_LSQ                             23
#define TOK_RSQ                             24
#define TOK_ENUM                            25
#define TOK_TYPE                            26
#define TOK_VAR                             27
#define TOK_VBAR                            28
#define TOK_INT                             29
#define TOK_STR                             30
#define TOK_BOOL                            31
#define TOK_FLOAT                           32
#define TOK_DATE                            33
#define TOK_TIME                            34
#define TOK_DATETIME                        35
#define TOK_ANY                             36
#define TOK_QUESTIONMARK                    37
#define TOK_ARRAY                           38
#define TOK_DICT                            39
#define TOK_TUPLE                           40
#define TOK_COLON                           41
#define TOK_ELSE                            42
#define TOK_ELSEIF                          43
#define TOK_IF                              44
#define TOK_FOR                             45
#define TOK_TO                              46
#define TOK_STEP                            47
#define TOK_DOWNTO                          48
#define TOK_SWITCH                          49
#define TOK_CASE                            50
#define TOK_INT_CONST                       51
#define TOK_STR_CONST                       52
#define TOK_TRUE                            53
#define TOK_FALSE                           54
#define TOK_EACH                            55
#define TOK_IN                              56
#define TOK_WITH                            57
#define TOK_WHILE                           58
#define TOK_UNTIL                           59
#define TOK_REPEAT                          60
#define TOK_TRY                             61
#define TOK_CATCH                           62
#define TOK_RAISE                           63
#define TOK_PRE                             64
#define TOK_POST                            65
#define TOK_ASSERT                          66
#define TOK_INVARIANT                       67
#define TOK_RESULT                          68
#define TOK_OR                              69
#define TOK_AND                             70
#define TOK_LE                              71
#define TOK_EQ                              72
#define TOK_GE                              73
#define TOK_NE                              74
#define TOK_PLUS                            75
#define TOK_MINUS                           76
#define TOK_DIV                             77
#define TOK_MOD                             78
#define TOK_IDIV                            79
#define TOK_NOT                             80
#define TOK_FLOAT_CONST                     81
#define TOK_NIL                             82
#define TOK_IS                              83
#define TOK_IIF                             84
#define TOK_OLD                             85
#define TOK_INHERITED                       86
#define TOK_LBR                             87
#define TOK_RBR                             88
