#define TOK_EOL                              1
#define TOK_IMPORT                           2
#define TOK_FROM                             3
#define TOK_COMMA                            4
#define TOK_FUNC                             5
#define TOK_ID                               6
#define TOK_LPAR                             7
#define TOK_RPAR                             8
#define TOK_ABSTRACT                         9
#define TOK_END                             10
#define TOK_PROC                            11
#define TOK_EVENT                           12
#define TOK_LOCAL                           13
#define TOK_OBSERVER                        14
#define TOK_AT                              15
#define TOK_ASSIGN                          16
#define TOK_DOT                             17
#define TOK_MULT                            18
#define TOK_LT                              19
#define TOK_GT                              20
#define TOK_CLASS                           21
#define TOK_LSQ                             22
#define TOK_RSQ                             23
#define TOK_ENUM                            24
#define TOK_TYPE                            25
#define TOK_VAR                             26
#define TOK_VBAR                            27
#define TOK_INT                             28
#define TOK_STR                             29
#define TOK_BOOL                            30
#define TOK_FLOAT                           31
#define TOK_DATE                            32
#define TOK_TIME                            33
#define TOK_DATETIME                        34
#define TOK_ANY                             35
#define TOK_QUESTIONMARK                    36
#define TOK_ARRAY                           37
#define TOK_DICT                            38
#define TOK_TUPLE                           39
#define TOK_COLON                           40
#define TOK_ELSE                            41
#define TOK_ELSEIF                          42
#define TOK_IF                              43
#define TOK_FOR                             44
#define TOK_TO                              45
#define TOK_STEP                            46
#define TOK_DOWNTO                          47
#define TOK_SWITCH                          48
#define TOK_CASE                            49
#define TOK_INT_CONST                       50
#define TOK_STR_CONST                       51
#define TOK_TRUE                            52
#define TOK_FALSE                           53
#define TOK_EACH                            54
#define TOK_IN                              55
#define TOK_WITH                            56
#define TOK_WHILE                           57
#define TOK_UNTIL                           58
#define TOK_REPEAT                          59
#define TOK_TRY                             60
#define TOK_CATCH                           61
#define TOK_RAISE                           62
#define TOK_PRE                             63
#define TOK_POST                            64
#define TOK_ASSERT                          65
#define TOK_INVARIANT                       66
#define TOK_RESULT                          67
#define TOK_OR                              68
#define TOK_AND                             69
#define TOK_LE                              70
#define TOK_EQ                              71
#define TOK_GE                              72
#define TOK_NE                              73
#define TOK_PLUS                            74
#define TOK_MINUS                           75
#define TOK_DIV                             76
#define TOK_MOD                             77
#define TOK_IDIV                            78
#define TOK_NOT                             79
#define TOK_FLOAT_CONST                     80
#define TOK_NIL                             81
#define TOK_IS                              82
#define TOK_IIF                             83
#define TOK_OLD                             84
#define TOK_INHERITED                       85
#define TOK_LBR                             86
#define TOK_RBR                             87
