#define TOK_EOL                              1
#define TOK_IMPORT                           2
#define TOK_FROM                             3
#define TOK_COMMA                            4
#define TOK_FUNC                             5
#define TOK_ID                               6
#define TOK_LPAR                             7
#define TOK_RPAR                             8
#define TOK_ABSTRACT                         9
#define TOK_END                             10
#define TOK_PROC                            11
#define TOK_EVENT                           12
#define TOK_OBSERVER                        13
#define TOK_AT                              14
#define TOK_ASSIGN                          15
#define TOK_DOT                             16
#define TOK_MULT                            17
#define TOK_LT                              18
#define TOK_GT                              19
#define TOK_CLASS                           20
#define TOK_LSQ                             21
#define TOK_RSQ                             22
#define TOK_ENUM                            23
#define TOK_TYPE                            24
#define TOK_VAR                             25
#define TOK_VBAR                            26
#define TOK_INT                             27
#define TOK_STR                             28
#define TOK_BOOL                            29
#define TOK_FLOAT                           30
#define TOK_DATE                            31
#define TOK_TIME                            32
#define TOK_DATETIME                        33
#define TOK_ANY                             34
#define TOK_QUESTIONMARK                    35
#define TOK_ARRAY                           36
#define TOK_DICT                            37
#define TOK_TUPLE                           38
#define TOK_COLON                           39
#define TOK_ELSE                            40
#define TOK_ELSEIF                          41
#define TOK_IF                              42
#define TOK_FOR                             43
#define TOK_TO                              44
#define TOK_STEP                            45
#define TOK_SWITCH                          46
#define TOK_CASE                            47
#define TOK_INT_CONST                       48
#define TOK_STR_CONST                       49
#define TOK_TRUE                            50
#define TOK_FALSE                           51
#define TOK_EACH                            52
#define TOK_IN                              53
#define TOK_WITH                            54
#define TOK_WHILE                           55
#define TOK_UNTIL                           56
#define TOK_REPEAT                          57
#define TOK_TRY                             58
#define TOK_CATCH                           59
#define TOK_OR                              60
#define TOK_AND                             61
#define TOK_LE                              62
#define TOK_EQ                              63
#define TOK_GE                              64
#define TOK_NE                              65
#define TOK_PLUS                            66
#define TOK_MINUS                           67
#define TOK_DIV                             68
#define TOK_MOD                             69
#define TOK_NOT                             70
#define TOK_FLOAT_CONST                     71
#define TOK_NIL                             72
#define TOK_IS                              73
#define TOK_IIF                             74
#define TOK_LBR                             75
#define TOK_RBR                             76
